export const INCIDENT_TYPES = {
  COLD_CHAIN_BREACH: "COLD_CHAIN_BREACH",
  LOW_BATTERY: "LOW_BATTERY",
  GEOFENCE_VIOLATION: "GEOFENCE_VIOLATION"
};

export const INCIDENT_SEVERITIES = {
  INFO: "INFO",
  WARNING: "WARNING",
  CRITICAL: "CRITICAL"
};